### ISSUE TITLE
Associate a color to team members when drawing graphs

### ISSUE THREAD

**Issue by Rolinh** [caarmen/scrumchatter#50]
I believe that this could be a good improvement not requiring much work.

Currently, there is no association between a team member and a color in the graphs. So if one looks at a graph, say the "average speaking time for team members", Bob speaking time is represented in blue in the pie chart. Now, one looks at the "speaking time for team meeting" and Bob speaking duration is represented in violet in the bar chart. This can be a little confusing and I think that always associating the same color to the same team member would be prevent any confusion.

**Comment by caarmen** [comment]
Good idea. This should be an easy one. There's a method buildMemberColorMap that iterates over the members and gets their color from the color list based on the index of that member in the member list. Instead of using the member's index in the list of members, it could use the hashcode of the member's name. The hashcode can be negative so a Math.abs is needed somewhere. 

https://github.com/caarmen/scrumchatter/blob/master/app/src/main/java/ca/rmen/android/scrumchatter/chart/MemberSpeakingTimeColumnChart.java


I can probably do this tomorrow, so don't worry if you don't have time for a pull request :-)  If you really want to do a PR though I'll give you credit in the app :-)

**Comment by caarmen** [comment]
This is included in release 1.5.1.

If you're interested in the code changes, they're here: https://github.com/caarmen/scrumchatter/pull/51

The charts aren't quite as pretty now :)  Previously they had a nice rainbow touch.  Now the order of the colors depends on which members talked the most.

It seems to render better with smaller teams.  I have data for two teams: 
* one with 9 members (where usually only about 6 actually showed up to meetings).
* one with 18 (!) members.  There are so many because of turnover.  In this case the colors don't display quite as nicely because there are often some repeat colors in the charts (a couple of members having the same color).  Maybe this could be improved by a better color selection in the "chart_colors" list here: https://github.com/caarmen/scrumchatter/blob/master/app/src/main/res/values/colors.xml

Maybe at some future point I'll add a setting to choose between "members always have the same chart colors" or "pretty charts". :)
